# Test for the Discussion Bot

name: Test-Discussion-Bot

# Trigger on any file change
on:
  push:

permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write
  pages: write
  id-token: write

jobs:
  bot-test:
    runs-on: ubuntu-24.04
    steps:
    - name: setup
      run: |
        pip install markdown
  
    - name: Check out the repository to the runner
      uses: actions/checkout@v4  

    - name: Test responses for the prepared discussions
      run: |
        cd test
        python test.py
        mv test/result.html index.html

    - name: Upload Test report
      uses: actions/upload-artifact@v4
      with:
        name: "Response-Bot_test-report"
        path: index.html

    - name: Setup Pages
      uses: actions/configure-pages@v4
              
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: 'result.html'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v3  # Note: v4 does not work!
